// <auto-generated />
namespace asp.netmvc5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialdbapp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialdbapp));
        
        string IMigrationMetadata.Id
        {
            get { return "201503130551274_initialdbapp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
