// <auto-generated />
namespace asp.netmvc5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class entityupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entityupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201503172301318_entityupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
