//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace asp.netmvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refugee
    {
        //public Refugee()
        //{
        //    this.Vaccines = new HashSet<Vaccine>();
        //}
    
        public int RefugeeId { get; set; }
        public long Patient_BarCode { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Laungage { get; set; }
        public string OriginCountry { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Patient_Vaccination> Patient_Vaccinations { get; set; }
    }
}
